// <auto-generated />
namespace RestAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class changeStatusToStringInDisbusement : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeStatusToStringInDisbusement));
        
        string IMigrationMetadata.Id
        {
            get { return "201902010806317_changeStatusToStringInDisbusement"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
